#!/usr/bin/env bash

# To use:
# ./run watch
# wach -o dist/js/bundle.js 'rld chrome'

# unofficial "strict mode": http://redsymbol.net/articles/unofficial-bash-strict-mode/
set -euo pipefail
IFS=$'\n\t'

export PATH="./node_modules/.bin:$PATH"

function bundle {
  ify browserify
}

function watch {
  # wach -o ./dist/js/bundle.js rld chrome &
  ify watchify --verbose &
  wait
}

function ify {
  $1 ./src/js/main.js \
    --debug \
    --transform babelify \
    --outfile ./dist/bundle.js \
    "${@:2}"
}

function help {
  echo instructions
}

eval "${1-help}"
